### ISSUE TITLE
CommandMineRewards compatibility

### ISSUE THREAD

**Issue by Lurreisper** [datatags/CommandMineRewards#1]
Hello, I would like to know if CommandMineRewards plugin isn't compatible with any of these plugins...

https://imgur.com/a/5hbtd1g

**Comment by datatags** [comment]
Well, unless there is an error I would say probably yes.  But to be sure you could make a copy of all your plugins and drop them in a plugins folder for a new server, and mess around and see what happens.  Really all the plugin does is if a specific block is broken, executes a command.  Shouldn't cause any compatibility issues for any reason I can think of.

**Comment by Lurreisper** [comment]
Ok, It worked, I din't put "allowedRegions".. But there was with this big error / crash: https://hastebin.com/ahuqisafeb.md

**Comment by datatags** [comment]
Stack dump says,
``Locked on:ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.recalculatePermissions(PermissiblePEX.java:178)``
For some reason it got hung on checking a permission from PEX.  I may need to implement some sort of permissions cache but I'm not really sure.  I would ask the author of PEX but he has stopped developing it, so... I'm not sure what to do.  You could try replacing PEX with LuckPerms.

**Comment by Lurreisper** [comment]
Oh... I'll see about that, thanks :/
