### ISSUE TITLE
Option to only give one reward on each time

### ISSUE THREAD

**Issue by Golicraft** [datatags/CommandMineRewards#3]
# I have already:

[X] Updated to the latest version of CMR. https://www.spigotmc.org/resources/commandminerewards.27316/
[X] Put CMR into debug mode and read the log for clues (see bottom of the resource page for step-by-step)
[X ] Included config.yml and debug.log in the issue in a .zip file. (Hint: drag and drop the .zip from File Explorer into this box.)

# Description of issue
Sometimes I get none rewards, sometimes I get multiple. I am trying to use this plugin as a lucky block plugin and it works pretty damn good without the issue in the title

Debug: https://pastebin.com/HMFFZywu
Config: https://pastebin.com/G103ST4T

Thank you in advance for making this plugin. It is great

I use Paperspigot 1.12.2 :)

**Comment by datatags** [comment]
I'm not super familiar with lucky block, so would you want it to give exactly 1 reward each time or up to 1 reward?

**Comment by Golicraft** [comment]
Hi thanks for the fast reply 🙂 I would like to be able to set max amount of rewards per time you break a block. For example I have 5 categories and I would like it to be able to only send 1 of the rewards for each sponge I break. And also that every time I break a sponge it gives one of the rewards and the chances describes how rare it should be. Thank you so much again

**Comment by datatags** [comment]
Ok, and I assume we should evaluate the rewards in a random order so it isn't weighted toward the first reward entries?

**Comment by Golicraft** [comment]
> 
> 
> Ok, and I assume we should evaluate the rewards in a random order so it isn't weighted toward the first reward entries?

The rewards should be chosen randomly thru the chances system if that was what you ment :)

**Comment by datatags** [comment]
I mean like should we evaluate the chances of each reward in a random order.  Like in your config, you have rewards 1 2 3 4 and 5.  My question was whether they should be shuffled before checking the chances, like should we check 2, then 4, then 3, then 5, then 1.  I'll probably just make it configurable though, since looking at your config I think you'd want it to be evaluated in order.

**Comment by Golicraft** [comment]
Oh I understand. For me it doesn't matter do what's best for you or what you think is the best. Thank you 🙂

**Comment by datatags** [comment]
Added in 20a90f5, reopen if there are any problems with it.  Thanks! :)
