### ISSUE TITLE
Players not getting rewards

### ISSUE THREAD

**Issue by leonardopilz** [datatags/CommandMineRewards#4]
how do i use title in config rewards
I have this doubt

commands:
            - cmr special title &test &6tester&b+ 10 20 10
console: This command can only be used by a player!

**Comment by datatags** [comment]
The `/cmr special` command is for testing only, in a reward you would use `!title` instead of `/cmr special title`, for example. I believe it gives more details with `/cmr help special`

**Comment by leonardopilz** [comment]
I'm using google translator sorry if I don't understand something

      commands:
      - give %player% example
      - broadcast %player% example
      - !title &aexample &6example 10 20 10 ?


/cmr help special title example server
example /cmr special title &aGood_job! &bYou_win! 20 60 20 I used it and it didn't work

console: This command can only be used by a player!

could you send me a command used in the config ready complete of title for me to understand the right

**Comment by datatags** [comment]
You have it almost right in your example, but I believe you need to put it in quotes since it starts with a "!"

`- '!title &aexample &6example 10 20 10'`

**Comment by leonardopilz** [comment]
It worked friend
thank you for your support :)

I didn't know I needed quotes

idea: could leave an example in the config for the players in some future update

**Comment by datatags** [comment]
That's probably a good idea. It should automatically wrap it in quotes if you use commands or the GUI to configure the plugin btw.

**Comment by leonardopilz** [comment]
Can CommandMineRewards add kill mobs and player together in plugin?
I can't find a plugin with this function to execute commands

I'm looking for a plugin that when killing mob or player has a chance to execute commands
your plugin can for many rewards by rewardID

I saw that you can add wheat
the other plantation items don't work : carrot , potato , beetroot , berries

**Comment by datatags** [comment]
> Can CommandMineRewards add kill mobs and player together in plugin? I can't find a plugin with this function to execute commands
> 
> I'm looking for a plugin that when killing mob or player has a chance to execute commands your plugin can for many rewards by rewardID

I'll think about it, but I'm thinking it would be a second plugin because CMR was built with only blocks in mind from the beginning, so it would be quite a change to add mob kills as well. Have you looked at this plugin: https://dev.bukkit.org/projects/mobhunting

> I saw that you can add wheat
> the other plantation items don't work : carrot , potato , beetroot , berries

I've literally just created a support server, I'll help you with it there: https://discord.gg/XwFERjbSQG

**Comment by leonardopilz** [comment]
Ok :)
